// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iynzcuyruupfquructqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5bnpjdXlydXVwZnF1cnVjdHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MjQ1NDAsImV4cCI6MjA1NDIwMDU0MH0.bkJzpwakDWi2WC15Z1aLhGTuzFTVWxQT-Gpd-PqRsUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);